## ruleset ##
# > Social
ruleset=🌏Proxy,[]GEOSITE,twitter
ruleset=🌏Proxy,[]GEOSITE,facebook
ruleset=🌏Proxy,[]GEOSITE,discord
ruleset=🎵TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list

# > Apple
ruleset=DIRECT,[]GEOSITE,apple
ruleset=DIRECT,[]GEOSITE,icloud

# > Telegram
#ruleset=🇳🇱NL,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TelegramNL/TelegramNL.list
#ruleset=🇺🇸US,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TelegramUS/TelegramUS.list
ruleset=🛩️Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list

# > OpenAI
ruleset=🌏Proxy,[]GEOSITE,openai

# > Game
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
## Steam
ruleset=DIRECT,[]DOMAIN-SUFFIX,cm.steampowered.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,steamserver.net
ruleset=DIRECT,[]DOMAIN-SUFFIX,gstore.val.smogfly.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,gstore.val.manlaxy.com
ruleset=DIRECT,[]IP-ASN,32590
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
ruleset=💨Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
## Console
ruleset=🕹️Console,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🕹️Console,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PlayStation/PlayStation.list
ruleset=🕹️Console,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Xbox/Xbox.list

# > Region
ruleset=🇨🇳TW,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=🇯🇵JP,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DMM/DMM.list
ruleset=🇯🇵JP,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Niconico/Niconico.list
ruleset=🇯🇵JP,https://raw.githubusercontent.com/EliceAM/Profiles/refs/heads/main/Clash/RuleSet/JP_region.list
## kindle ntp ##
ruleset=🇨🇳TW,[]DOMAIN-SUFFIX,dcape-na.amazon.com

# > Brand
ruleset=📌Brand,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/MEGA/MEGA.list

# > Media
#ruleset=🌏Proxy,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TIDAL/TIDAL.list
ruleset=🎧Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🌏Proxy,[]DOMAIN-KEYWORD,emby

# > Google
ruleset=📢Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTubeMusic/YouTubeMusic.list
ruleset=📢Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTubeMusic/YouTube.list
ruleset=📢Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=📢Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list

# > Microsoft
#ruleset=DIRECT,[]GEOSITE,microsoft
## GitHub
ruleset=🌏Proxy,[]GEOSITE,gitHub

# > PayPal
ruleset=DIRECT,[]GEOSITE,paypal

# > Direct
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
ruleset=DIRECT,https://raw.githubusercontent.com/EliceAM/Profiles/main/Clash/RuleSet/Direct.list

# > Proxy
ruleset=🌏Proxy,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Reddit/Reddit.list
ruleset=🌏Proxy,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EHGallery/EHGallery.list
ruleset=🌏Proxy,https://raw.githubusercontent.com/EliceAM/Profiles/main/Clash/RuleSet/Proxy.list
ruleset=🌏Proxy,[]GEOSITE,geolocation-!cn

ruleset=🚩Final,[]FINAL

## proxy_groups ##
custom_proxy_group=🕹️Console`select`[]DIRECT`[]🇭🇰HK`[]🇯🇵JP`[]🇺🇸US`[]⚡️DMITLAC
custom_proxy_group=💨Steam`select`[]DIRECT`[]🇭🇰HK`[]🇯🇵JP`[]🇺🇸US`[]⚡️DMITLAC
custom_proxy_group=🛩️Telegram`select`[]🇸🇬SG`[]🇺🇸US`[]⚡️DMITLAC`[]🇳🇱NL
custom_proxy_group=🎧Spotify`select`[]DIRECT`[]🇨🇳TW`[]🇯🇵JP`[]🇺🇸US
#custom_proxy_group=📺Emby`select`[]🇭🇰HK`[]🇨🇳TW`[]🇯🇵JP`[]🇸🇬SG`[]🇺🇸US
custom_proxy_group=🎵TikTok`select`[]🇭🇰HK`[]🇨🇳TW`[]🇯🇵JP`[]🇸🇬SG`[]🇺🇸US
#custom_proxy_group=⚛OpenAI`select`[]🇭🇰HK`[]🇨🇳TW`[]🇦🇺AU`[]🇯🇵JP`[]🇸🇬SG`[]🇺🇸US`[]🇬🇧UK`[]🇳🇱NL
custom_proxy_group=📢Google`select`[]🇭🇰HK`[]🇨🇳TW`[]🇦🇺AU`[]🇯🇵JP`[]🇸🇬SG`[]🇺🇸US`[]⚡️DMITLAC`[]🇬🇧UK`[]🇳🇱NL
custom_proxy_group=📌Brand`select`[]🇭🇰HK`[]🇨🇳TW`[]🇦🇺AU`[]🇯🇵JP`[]🇸🇬SG`[]🇺🇸US`[]⚡️DMITLAC`[]🇬🇧UK`[]🇳🇱NL
custom_proxy_group=🌏Proxy`select`[]🇭🇰HK`[]🇨🇳TW`[]🇦🇺AU`[]🇯🇵JP`[]🇸🇬SG`[]🇺🇸US`[]⚡️DMITLAC`[]🇬🇧UK`[]🇳🇱NL
custom_proxy_group=🚩Final`select`[]DIRECT`[]🌏Proxy
custom_proxy_group=⚡️DMITLAC`url-test`(DMITLAC)`http://cp.cloudflare.com/generate_204`180,,60
custom_proxy_group=🇭🇰HK`url-test`^(?=.*(香港|HK))(?!.*(3x|5x)).*`http://cp.cloudflare.com/generate_204`300,,100`http://cp.cloudflare.com/generate_204`180,,60
custom_proxy_group=🇨🇳TW`url-test`(台|新北|彰化|TW)`http://cp.cloudflare.com/generate_204`180,,60
custom_proxy_group=🇯🇵JP`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP)`http://cp.cloudflare.com/generate_204`180,,60
custom_proxy_group=🇸🇬SG`url-test`(新加坡|坡|狮城|SG)`http://cp.cloudflare.com/generate_204`180,,60
custom_proxy_group=🇺🇸US`url-test`^(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|水牛城|亚特兰大|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA))(?!.*(3x|5x)).*`http://cp.cloudflare.com/generate_204`180,,60
custom_proxy_group=🇬🇧UK`url-test`^(?!.*?(3x)).*(英国)`http://cp.cloudflare.com/generate_204`180,,60
custom_proxy_group=🇦🇺AU`url-test`(澳大利亚|澳洲|AU)`http://cp.cloudflare.com/generate_204`180,,60
custom_proxy_group=🇳🇱NL`url-test`^(?!.*?(3x)).*(荷兰)`http://cp.cloudflare.com/generate_204`180,,60


## common ##
#include_remarks=(?=.*(香港|台湾|新加坡|日本|美国|荷兰|法国|德国|卢森堡))
exclude_remarks=(移动)
enable_rule_generator=true
overwrite_original_rules=true
