[custom]
# Local Area Network
ruleset=DIRECT,[]IP-CIDR,192.168.0.0/16
ruleset=DIRECT,[]IP-CIDR,10.0.0.0/8
ruleset=DIRECT,[]IP-CIDR,172.16.0.0/12
ruleset=DIRECT,[]IP-CIDR,127.0.0.0/8
ruleset=DIRECT,[]IP-CIDR,100.64.0.0/10
ruleset=DIRECT,[]IP-CIDR,224.0.0.0/4
ruleset=DIRECT,[]IP-CIDR,fe80::/10

# Hnair
ruleset=DIRECT,[]DOMAIN-SUFFIX,hnair.com
ruleset=DIRECT,[]DOMAIN-KEYWORD,hnagroup

# Arcaea
ruleset=DIRECT,[]DOMAIN-SUFFIX,lowiro.com

# Emby
ruleset=🎬Emby,[]DOMAIN-SUFFIX,emby.wtf

# Zhihu
ruleset=REJECT,[]IP-CIDR,118.89.204.198/32,no-resolve

# Unbreak
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list

# Guard
ruleset=🛑Guard,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑Guard,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

# Google
ruleset=📢Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Google/Google.list

# Microsoft
ruleset=🖥️Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Microsoft/Microsoft.list

# Telegram
ruleset=📱Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Telegram/Telegram.list

# Steam
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/SteamCN/SteamCN.list
ruleset=🎮Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Steam/Steam.list

# Console
ruleset=🕹️Console,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Xbox/Xbox.list
ruleset=🕹️Console,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Nintendo/Nintendo.list
ruleset=🕹️Console,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/PlayStation/PlayStation.list

# JP Region
ruleset=🇯🇵Japon,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Dmm.list
ruleset=🇯🇵Japon,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Niconico.list
ruleset=🇯🇵Japon,[]DOMAIN-SUFFIX,mora.jp
ruleset=🇯🇵Japon,[]DOMAIN-SUFFIX,dlsite.com

# YouTube
ruleset=📹YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/YouTube/YouTube.list
ruleset=📹YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/YouTubeMusic/YouTubeMusic.list

# Spotify
ruleset=🎵Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Spotify/Spotify.list

# Media
ruleset=🎥GlobalMedia,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/GlobalMedia/GlobalMedia.list
ruleset=📺ChinaMedia,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/ChinaMedia/ChinaMedia.list

# PayPal
ruleset=💰PayPal,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/PayPal/PayPal.list

# Global
ruleset=🌍Global,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Nvidia/Nvidia.list
ruleset=🌍Global,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Facebook/Facebook.list
ruleset=🌍Global,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/GitHub/GitHub.list
ruleset=🌍Global,https://raw.githubusercontent.com/EliceAM/Profiles/main/Clash/RuleSet/ProxyList.list
ruleset=🌍Global,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list

# Appstore
ruleset=🍎Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Apple/Apple.list

# China Domain
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Download/Download.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list

# China IP
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=🚩Final,[]FINAL


custom_proxy_group=🌍Global`select`[]🎌0.3×`[]🇭🇰HK`[]🇨🇳TW`[]🇸🇬SG`[]🇯🇵JP`[]🇺🇸US
custom_proxy_group=📢Google`select`[]🇸🇬SG`[]🇭🇰HK`[]🇯🇵JP`[]🇺🇸US
custom_proxy_group=🖥️Microsoft`select`[]DIRECT`[]🌍Global
custom_proxy_group=📱Telegram`select`[]🇸🇬SG`[]🇺🇸US`[]🇭🇰HK
custom_proxy_group=🎮Steam`select`[]🇭🇰HK`[]DIRECT
custom_proxy_group=🕹️Console`select`[]DIRECT`[]🇭🇰HK
custom_proxy_group=🇯🇵Japon`select`[]🇯🇵JP`[]🌍Global
custom_proxy_group=📹YouTube`select`[]🎌0.3×`[]🇺🇸US`[]🇭🇰HK
custom_proxy_group=🎵Spotify`select`[]DIRECT`[]🇯🇵JP
custom_proxy_group=🎬Emby`select`[]🎌0.3×`[]DIRECT`[]🇭🇰HK
custom_proxy_group=🎥GlobalMedia`select`[]🎌0.3×`[]🇨🇳TW`[]🇭🇰HK`[]🇸🇬SG
custom_proxy_group=📺ChinaMedia`select`[]DIRECT`[]🇨🇳TW`[]🇭🇰HK
custom_proxy_group=💰PayPal`select`[]🇺🇸US`[]DIRECT
custom_proxy_group=🍎Apple`select`[]DIRECT`[]🇺🇸US
custom_proxy_group=🛑Guard`select`[]REJECT`[]DIRECT
custom_proxy_group=🚩Final`select`[]DIRECT`[]🎌0.3×`[]🌍Global
custom_proxy_group=🎌0.3×`url-test`(0.3)`http://cp.cloudflare.com/generate_204`600,,150
custom_proxy_group=🇭🇰HK`url-test`(港|HK|Hong Kong)`http://cp.cloudflare.com/generate_204`600,,150
custom_proxy_group=🇯🇵JP`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://cp.cloudflare.com/generate_204`600,,200
custom_proxy_group=🇺🇸US`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://cp.cloudflare.com/generate_204`600,,250
custom_proxy_group=🇨🇳TW`url-test`(台|新北|彰化|TW|Taiwan)`http://cp.cloudflare.com/generate_204`600,,150
custom_proxy_group=🇸🇬SG`url-test`(新加坡|坡|狮城|SG|Singapore)`http://cp.cloudflare.com/generate_204`600,,150

enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://raw.githubusercontent.com/EliceAM/Profiles/main/Clash/Outbound.yaml
