log:
  level: info
  file: "/tmp/mosdns.log"

plugins:
  ################## 数据源 ##################
  - tag: whitelist
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/whitelist.txt
        - /etc/mosdns/rule/ddnslist.txt
        - /var/mosdns/geosite_tencent.txt
        - /var/mosdns/geosite_apple.txt
        - /var/mosdns/geosite_microsoft@cn.txt
        
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - /var/mosdns/geosite_cn.txt
        - /var/mosdns/geosite_tld-cn.txt

  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/greylist.txt
        - /var/mosdns/geosite_gfw.txt
        - /var/mosdns/geosite_google.txt
        - /var/mosdns/geosite_steam.txt

  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - /var/mosdns/geoip_cn.txt

  ################## 逻辑执行序列 ##################
  
  #纯净国内转发 (SmartDNS)
  - tag: local_forward
    type: sequence
    args:
      - exec: forward udp://192.168.10.3:5353
      - exec: ttl 5-5

  #Clash 转发 (Fake-IP)
  - tag: clash_forward
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: forward udp://127.0.0.1:7874
      - exec: ttl 1-1

  # fallback的primary服务器, 返回国内ip则accept, 返回非国内ip则drop
  - tag: local_sequence
    type: sequence
    args:
      - exec: $local_forward
      - matches: resp_ip $geoip_cn
        exec: accept
      - exec: drop_resp

  # fallback的secondary服务器, 返回非国内ip则添加至ipset, 返回国内ip只接受不会添加ipset
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $clash_forward
      - exec: accept

  # fallback sequence
  - tag: fallback
    type: fallback
    args:
      primary: local_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true


  ################## 主运行逻辑 ##################

  - tag: main_sequence
    type: sequence
    args:
    
      # 屏蔽PTR和DNSSEC，解决ios系统的一些问题
      - matches: qtype 12 65
        exec: reject 0  
      - matches: "qname keyword::" # 无效域名
        exec: reject 3
        
      - matches: 
          - qname $whitelist
        exec: $local_forward
      - matches: has_resp
        exec: accept
        
      - matches: 
          - qname $geosite_no_cn
        exec: $clash_forward
      - matches: has_resp
        exec: accept

      - matches: 
          - qname $geosite_cn
        exec: $local_forward
      - matches: has_resp
        exec: accept

      - exec: $fallback

  ################## 入口服务 ##################
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :5353
