log:
  level: info
  file: "/var/log/mosdns.log"
  
plugins:
  ################## 数据源 ##################

  - tag: geosite_lan
    type: domain_set
    args:
      files:
        - /var/mosdns/geosite_private.txt
        
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/whitelist.txt
        - /etc/mosdns/rule/ddnslist.txt
        - /var/mosdns/geosite_tld-cn.txt
        - /var/mosdns/geosite_cloudflare-cn.txt
        - /var/mosdns/geosite_cn.txt
        - /var/mosdns/geosite_apple.txt
        - /var/mosdns/geosite_microsoft@cn.txt
        - /var/mosdns/geosite_akamai@cn.txt
        
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/greylist.txt
        - /var/mosdns/geosite_geolocation-!cn.txt
        
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - /var/mosdns/geoip_cn.txt
        
  ################## 逻辑执行序列 ##################

  # 国内转发 (SmartDNS)
  - tag: local_forward
    type: sequence
    args:
      - exec: forward 192.168.10.3:6353
      - exec: ttl 5-5
  
  # Fake-IP转发 (Clash)
  - tag: clash_forward
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: forward 127.0.0.1:7874
      - exec: ttl 1-1

  # fallback的primary服务器, 返回国内ip则accept, 返回非国内ip则drop
  - tag: primary_sequence
    type: sequence
    args:
      - exec: $local_forward
      - matches: resp_ip $geoip_cn
        exec: accept
      - exec: drop_resp
  # fallback的secondary服务器
  - tag: secondary_sequence
    type: sequence
    args:
      - exec: $clash_forward
      - exec: query_summary "HIT_FAKEIP"
 
  # fallback sequence
  - tag: fallback
    type: fallback
    args:
      primary: primary_sequence
      secondary: secondary_sequence
      threshold: 400
      always_standby: false

  ################## 主运行逻辑 ##################

  - tag: main_sequence
    type: sequence
    args:
      - matches: 
          - qname $geosite_lan
        exec: reject 5
        
      - matches: 
          - qname $geosite_cn
        exec: goto local_forward
        
      - matches: 
          - qname $geosite_no_cn
        exec: goto clash_forward

      - exec: $fallback
      - exec: query_summary "LEAK"
      
  ################## 入口服务 ##################
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :6353
